import { createClient as createServerSupabase } from '@/lib/supabase/server';
import MoodOverview from '@/components/dashboard/MoodOverview';
import MoodTrendChart from '@/components/dashboard/MoodTrendChart';
import BiggestWins from '@/components/dashboard/BiggestWins';
import TopicsCloud from '@/components/dashboard/TopicsCloud';
import EmotionalPatterns from '@/components/dashboard/EmotionalPatterns';
import AIReflection from '@/components/dashboard/AIReflection';
import ActivityHeatmap from '@/components/dashboard/ActivityHeatmap';
import { DashboardData, TimeFrame } from '@/lib/types/database';
import { format } from 'date-fns';
import { redirect } from 'next/navigation';

async function getDashboardData(supabase: any, userId: string, timeframe: TimeFrame): Promise<DashboardData> {
  const latestDate = new Date();
  let cutoff = new Date(latestDate);
  if (timeframe === 'week') cutoff.setDate(latestDate.getDate() - 7);
  else if (timeframe === 'month') cutoff.setDate(latestDate.getDate() - 30);
  else cutoff.setDate(latestDate.getDate() - 365);

  const cutoffStr = cutoff.toISOString().split('T')[0];

  const { data: moodHistory } = await supabase
    .from('mood_history')
    .select('*')
    .eq('user_id', userId)
    .gte('date', cutoffStr)
    .order('date', { ascending: true });

  const avgMood = moodHistory && moodHistory.length ? Math.round(moodHistory.reduce((s: number, m: any) => s + m.mood_score, 0) / moodHistory.length) : 0;

  const recentCount = Math.max(1, Math.floor((moodHistory?.length ?? 0) / 3));
  const recent = (moodHistory || []).slice(-recentCount);
  const older = (moodHistory || []).slice(0, -recentCount);
  const recentAvg = recent.length ? recent.reduce((s: number, m: any) => s + m.mood_score, 0) / recent.length : avgMood;
  const olderAvg = older.length ? older.reduce((s: number, m: any) => s + m.mood_score, 0) / older.length : avgMood;

  const trend: 'up' | 'down' | 'stable' = recentAvg - olderAvg > 5 ? 'up' : recentAvg - olderAvg < -5 ? 'down' : 'stable';

  const { data: analyses } = await supabase
    .from('ai_entry_analysis')
    .select('*')
    .gte('created_at', cutoffStr)
    .order('created_at', { ascending: false });

  const { data: profile } = await supabase.from('user_ai_profile').select('*').eq('user_id', userId).single();

  const { data: totalEntriesRes } = await supabase
    .from('journal_entries')
    .select('id', { count: 'exact' })
    .eq('user_id', userId);

  const totalEntries = Array.isArray(totalEntriesRes) ? totalEntriesRes.length : 0;

  // Simple streak calc
  const dates = (moodHistory || []).map((m: any) => m.date).sort();
  let currentStreak = 0;
  let longestStreak = 0;
  let streak = 0;
  let lastDate: Date | null = null;

  for (const d of dates) {
    const dt = new Date(d);
    if (!lastDate) {
      streak = 1;
    } else {
      const diff = (dt.getTime() - lastDate.getTime()) / (1000 * 60 * 60 * 24);
      if (diff === 1) streak += 1;
      else streak = 1;
    }
    if (streak > longestStreak) longestStreak = streak;
    lastDate = dt;
  }

  // current streak: count backwards from latest date
  if (dates.length) {
    let cs = 1;
    for (let i = dates.length - 1; i > 0; i--) {
      const cur = new Date(dates[i]);
      const prev = new Date(dates[i - 1]);
      const diff = (cur.getTime() - prev.getTime()) / (1000 * 60 * 60 * 24);
      if (diff === 1) cs += 1;
      else break;
    }
    currentStreak = cs;
  }

  const biggestWins = (analyses || []).map((a: any) => a.biggest_win).filter(Boolean);

  const aiReflection = timeframe === 'week' ? 'Recent week summary generated by AI.' : timeframe === 'month' ? 'Monthly reflection generated by AI.' : 'Yearly reflection generated by AI.';

  return {
    moodHistory: moodHistory || [],
    averageMood: avgMood,
    moodTrend: trend,
    biggestWins: biggestWins.slice(0, timeframe === 'week' ? 2 : timeframe === 'month' ? 4 : 6),
    recurringTopics: profile?.recurring_topics || [],
    emotionalPatterns: profile?.emotional_patterns || [],
    aiReflection,
    totalEntries,
    currentStreak,
    longestStreak,
    entryDates: (moodHistory || []).map((m: any) => m.date),
    analyses: analyses || [],
  };
}

export default async function DashboardPage({ searchParams }: any) {
  const timeframe = (searchParams?.timeframe as TimeFrame) || 'month';
  const supabase = await createServerSupabase();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return redirect('/auth/login');

  const data = await getDashboardData(supabase, user.id, timeframe);

  return (
    <div className="h-full w-full bg-background relative overflow-hidden flex flex-col">
      <div className="flex-1 w-full relative z-10 overflow-y-auto px-4 sm:px-8 py-8 custom-scrollbar">
        <div className="max-w-6xl mx-auto w-full space-y-6 pb-24">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
            <div>
              <h1 className="text-3xl font-bold mb-1">Your AI Mirror</h1>
              <p className="text-muted-foreground text-sm">Visualize your emotional evolution over time.</p>
            </div>
          </div>

          <ActivityHeatmap entries={data.moodHistory} totalEntries={data.totalEntries} currentStreak={data.currentStreak} longestStreak={data.longestStreak} timeframe={timeframe} />

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 pt-4">
            <div className="lg:col-span-2 space-y-6">
              <MoodOverview score={data.averageMood} trend={data.moodTrend} />
              <MoodTrendChart data={data.moodHistory} timeframe={timeframe} />
              <AIReflection reflection={data.aiReflection} />
            </div>

            <div className="space-y-6">
              <BiggestWins wins={data.biggestWins} />
              <TopicsCloud topics={data.recurringTopics} />
              <EmotionalPatterns patterns={data.emotionalPatterns} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
